### ISSUE TITLE
Can't add relative timelocks (nSequence field) to transaction using the playground

### ISSUE THREAD

**Issue by mr-zwets** [rkalis/cashscript-playground#15]
You can't add relative timelocks (nSequence field) to transaction using the playground. Because of this it's not possible to make transactions with the Licho's Mecenas[#](https://cashscript.org/docs/language/examples#lichos-mecenas) example smart contract in the playground.

**Comment by rkalis** [comment]
We'll move this issue to the Next.js version of the playground.
