### ISSUE TITLE
contract balance doesn't update after making a transaction

### ISSUE THREAD

**Issue by mr-zwets** [rkalis/cashscript-playground#7]
Confusing that contract balance doesn't update after making a transaction to or from the smart contract address.
Currently you have to re-press the "create" button, which is a slight inconvenience

**Comment by mr-zwets** [comment]
solved in the next-js version -> https://github.com/mr-zwets/next-cashscript-playground

**Comment by rkalis** [comment]
We're switching to the Next.js version once we launch v0.8.0 in production.
