### ISSUE TITLE
Change naming of the networks to testnet3 & testnet4

### ISSUE THREAD

**Issue by mr-zwets** [rkalis/cashscript-playground#9]
Currently "testnet" means testnet3 and "staging" is just testnet4.
It would be better if this terminology was used.
A staging network only spun up half a year before a network upgrade can be named "chipnet".
This change should happen in Cashscript first and then it can be easily extended to the cashscript playground.

**Comment by rkalis** [comment]
Thanks for the PR, new changes are deployed!
